# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [61]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.16200947 0.32678589 0.37737722 0.38544141 0.22164532]
  [0.20094691 0.71953877 0.85882842 0.17515157 0.83233367]
  [0.61210126 0.21205259 0.4387205  0.69127042 0.60735831]]

 [[0.44310272 0.12536778 0.59850804 0.50391944 0.27833525]
  [0.52037085 0.9065045  0.0522971  0.41024422 0.42227668]
  [0.47636112 0.85412024 0.80035748 0.98212291 0.37744969]]]


In [62]:
# Method 2

a_2= np.random.rand(2,3,5)
print(b)



[[[0.50352289 0.88707335 0.62252392 0.36028537 0.70980602]
  [0.23606727 0.56691126 0.16786383 0.29072155 0.73325306]
  [0.04076855 0.444809   0.38195468 0.14131819 0.95071971]]

 [[0.32674546 0.6324773  0.12438934 0.9140036  0.54437338]
  [0.01339774 0.32648196 0.82546694 0.48077896 0.15241742]
  [0.8410231  0.24836618 0.85622941 0.91495181 0.23111543]]]


In [63]:
# Method 3

a_3= np.random.randint(0,100,30).reshape(2,3,5)
print(c)


[[[73 53 27 35 20]
  [83 67 74 49 66]
  [72 97 82 53 23]]

 [[39 80 42 69 37]
  [38 27 81 60 52]
  [41 65 57 56 86]]]


#### 4. Print *a*.


In [66]:
# your code here
print(a)

[[[0.16200947 0.32678589 0.37737722 0.38544141 0.22164532]
  [0.20094691 0.71953877 0.85882842 0.17515157 0.83233367]
  [0.61210126 0.21205259 0.4387205  0.69127042 0.60735831]]

 [[0.44310272 0.12536778 0.59850804 0.50391944 0.27833525]
  [0.52037085 0.9065045  0.0522971  0.41024422 0.42227668]
  [0.47636112 0.85412024 0.80035748 0.98212291 0.37744969]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [67]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [68]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [69]:
# your code here
if ((a.size)) == int((b.size)):
    print("They have the same size")
else:
    print("They have different size")

They have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [70]:
# your answer here

try:
    sum_ab = a + b
    print(sum_ab)
except:
    print("Dimmensions are not the same (shape) so its not possible to sum the arrays, so this print is an exception because is an error")


Dimmensions are not the same (shape) so its not possible to sum the arrays, so this print is an exception because is an error


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [71]:
# your code here
c = np.transpose(b, (1,2,0))
print((c.shape))

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [77]:
# your code/answer here
d = a + c
print(d)

[[[1.16200947 1.32678589 1.37737722 1.38544141 1.22164532]
  [1.20094691 1.71953877 1.85882842 1.17515157 1.83233367]
  [1.61210126 1.21205259 1.4387205  1.69127042 1.60735831]]

 [[1.44310272 1.12536778 1.59850804 1.50391944 1.27833525]
  [1.52037085 1.9065045  1.0522971  1.41024422 1.42227668]
  [1.47636112 1.85412024 1.80035748 1.98212291 1.37744969]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [95]:
# your code/answer here

print(a)
print(d)

[[[0.16200947 0.32678589 0.37737722 0.38544141 0.22164532]
  [0.20094691 0.71953877 0.85882842 0.17515157 0.83233367]
  [0.61210126 0.21205259 0.4387205  0.69127042 0.60735831]]

 [[0.44310272 0.12536778 0.59850804 0.50391944 0.27833525]
  [0.52037085 0.9065045  0.0522971  0.41024422 0.42227668]
  [0.47636112 0.85412024 0.80035748 0.98212291 0.37744969]]]
[[[1.16200947 1.32678589 1.37737722 1.38544141 1.22164532]
  [1.20094691 1.71953877 1.85882842 1.17515157 1.83233367]
  [1.61210126 1.21205259 1.4387205  1.69127042 1.60735831]]

 [[1.44310272 1.12536778 1.59850804 1.50391944 1.27833525]
  [1.52037085 1.9065045  1.0522971  1.41024422 1.42227668]
  [1.47636112 1.85412024 1.80035748 1.98212291 1.37744969]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [91]:
# your code here
e = a * c
print(e)


[[[0.16200947 0.32678589 0.37737722 0.38544141 0.22164532]
  [0.20094691 0.71953877 0.85882842 0.17515157 0.83233367]
  [0.61210126 0.21205259 0.4387205  0.69127042 0.60735831]]

 [[0.44310272 0.12536778 0.59850804 0.50391944 0.27833525]
  [0.52037085 0.9065045  0.0522971  0.41024422 0.42227668]
  [0.47636112 0.85412024 0.80035748 0.98212291 0.37744969]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [93]:
# your code/answer here

if e.all() == a.all():
    print("Si son iguales multiplicaste por 1!")
else:
    print("no son iguales")



Si son iguales multiplicaste por 1


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [94]:
# your code here

d_mean = np.mean(d)
d_max = np.max(d)
d_min = np.min(d)

print(d_mean)
print(d_max)
print(d_min)

1.4857633237613983
1.982122908336597
1.0522970994973864


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [47]:
# your code here
f = np.empty((2,3,5),dtype=float)
print(f)

[[[0.50352289 0.88707335 0.62252392 0.36028537 0.70980602]
  [0.23606727 0.56691126 0.16786383 0.29072155 0.73325306]
  [0.04076855 0.444809   0.38195468 0.14131819 0.95071971]]

 [[0.32674546 0.6324773  0.12438934 0.9140036  0.54437338]
  [0.01339774 0.32648196 0.82546694 0.48077896 0.15241742]
  [0.8410231  0.24836618 0.85622941 0.91495181 0.23111543]]]
[[0.50352289 0.88707335 0.62252392 0.36028537 0.70980602]
 [0.23606727 0.56691126 0.16786383 0.29072155 0.73325306]
 [0.04076855 0.444809   0.38195468 0.14131819 0.95071971]]
[[0.32674546 0.6324773  0.12438934 0.9140036  0.54437338]
 [0.01339774 0.32648196 0.82546694 0.48077896 0.15241742]
 [0.8410231  0.24836618 0.85622941 0.91495181 0.23111543]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [105]:
# your code here
d_mean = np.mean(d)
d_max = np.max(d)
d_min = np.min(d)

result = []
for i in d:
    for j in i:
        for k in j:
            if k > d_min and k < d_mean:
                result.append(25)
            elif k > d_mean and k < d_max:
                result.append(75)
            elif k == d_mean:
                result.append(50)
            elif k == d_min:
                result.append(0)
            elif k == d_max:
                result.append(100)

f = np.array(result).reshape(2,3,5)
print(f)

print(f' Esta es la media: {d_mean}')
print(f' Este es el máximo: {d_max}')
print(f' Este es el mínimo: {d_min}')


[[[ 25  25  25  25  25]
  [ 25  75  75  25  75]
  [ 75  25  25  75  75]]

 [[ 25  25  75  75  25]
  [ 75  75   0  25  25]
  [ 25  75  75 100  25]]]
 Esta es la media: 1.4857633237613983
 Este es el máximo: 1.982122908336597
 Este es el mínimo: 1.0522970994973864


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [106]:
# your code here

print(d)
print(f)

[[[1.16200947 1.32678589 1.37737722 1.38544141 1.22164532]
  [1.20094691 1.71953877 1.85882842 1.17515157 1.83233367]
  [1.61210126 1.21205259 1.4387205  1.69127042 1.60735831]]

 [[1.44310272 1.12536778 1.59850804 1.50391944 1.27833525]
  [1.52037085 1.9065045  1.0522971  1.41024422 1.42227668]
  [1.47636112 1.85412024 1.80035748 1.98212291 1.37744969]]]
[[[ 25  25  25  25  25]
  [ 25  75  75  25  75]
  [ 75  25  25  75  75]]

 [[ 25  25  75  75  25]
  [ 75  75   0  25  25]
  [ 25  75  75 100  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [109]:
# your code here
print(result)
result2 = []
for i in result:
    if i==0:
        result2.append('A')
    elif i == 25:
        result2.append('B')
    elif i == 50:
        result2.append('C')
    elif i == 75:
        result2.append('D')
    elif i == 100:
        result2.append('E')

g = np.array(result2).reshape(2,3,5)
print(g)

[25, 25, 25, 25, 25, 25, 75, 75, 25, 75, 75, 25, 25, 75, 75, 25, 25, 75, 75, 25, 75, 75, 0, 25, 25, 25, 75, 75, 100, 25]
[[['B' 'B' 'B' 'B' 'B']
  ['B' 'D' 'D' 'B' 'D']
  ['D' 'B' 'B' 'D' 'D']]

 [['B' 'B' 'D' 'D' 'B']
  ['D' 'D' 'A' 'B' 'B']
  ['B' 'D' 'D' 'E' 'B']]]
